services:
  - type: web
    plan: free
    name: devindes
    buildCommand: "./deploy.sh"
    startCommand: "python -m gunicorn core.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generate: True
      - key: DJANGO_SETTINGS_MODULE
        value: "core.settings.prod"
      - key: WEB_CONCURRENCY
        value: "4"
