# Generated by Django 5.0.7 on 2024-08-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('client_type', models.CharField(choices=[('1', 'Petite Entreprise (1-10 employés)'), ('2', 'Moyenne Entreprise (11-50 employés)'), ('3', 'Grande Entreprise (50+ employés)'), ('4', 'Startup'), ('5', 'Particulier'), ('6', 'Association')], max_length=1)),
                ('duration', models.IntegerField()),
                ('description', models.TextField()),
                ('daily_rate', models.IntegerField()),
                ('contact', models.CharField(choices=[('1', 'Réseau'), ('2', 'Linkedin'), ('3', 'Plateforme de Freelance (Malt, Comet, Creme de la Creme...)')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
