# Generated by Django 5.0.7 on 2024-08-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='experience_level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
