# Generated by Django 5.0.7 on 2024-08-31 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_mission_experience_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='mission',
            name='personal_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='language_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='language_a', to='missions.language'),
        ),
        migrations.AddField(
            model_name='mission',
            name='language_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='language_b', to='missions.language'),
        ),
        migrations.AddField(
            model_name='mission',
            name='stack_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stack_a', to='missions.technology'),
        ),
        migrations.AddField(
            model_name='mission',
            name='stack_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stack_b', to='missions.technology'),
        ),
        migrations.AddField(
            model_name='mission',
            name='stack_c',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stack_c', to='missions.technology'),
        ),
    ]
