# Generated by Django 5.0.7 on 2024-09-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0004_alter_language_options_alter_mission_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='stack',
        ),
        migrations.AddField(
            model_name='mission',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='missions', to='missions.language'),
        ),
        migrations.AddField(
            model_name='mission',
            name='stack',
            field=models.ManyToManyField(blank=True, related_name='missions', to='missions.technology'),
        ),
    ]
